package com.GRANDEUR.GrandeurBackend.models;


import javax.persistence.*;
import java.io.Serializable;

@Entity
public class User implements Serializable {
    @Id // primary key annotation //
    // Automatically generated and incremented //
    @GeneratedValue(strategy = GenerationType.AUTO)
    // userId that's used to uniquely identify for every user  (automatically  generated by JPA) //
    private Long userId;

    private String name;  // userName //

    @Column(nullable = false, updatable = false) // making the email column non-null and non update-able //
    private String email; // userEmail //

    private String password; // userPassword //

    // default Constructor //
    public User(){

    }

    // Parameterized constructor //
    public User(Long userId, String name, String email, String password) {
        this.userId = userId;
        this.name = name;
        this.email = email;
        this.password = password;
    }


    // GETTERS AND SETTERS for all the variables //
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


    // To String //
    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                '}';
    }
}
